ALTER TABLE "User" ADD COLUMN "profileZoom" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "User" ADD COLUMN "profileFocusX" DOUBLE PRECISION NOT NULL DEFAULT 50;
ALTER TABLE "User" ADD COLUMN "profileFocusY" DOUBLE PRECISION NOT NULL DEFAULT 50;
